parser: babel-eslint

extends:
  - standard
  - plugin:ava/recommended
  - plugin:node/recommended

plugins:
  - ava
  - node
  - promise
  - standard

settings:
  node:
    allowModules:
      - electron
